### PR TITLE
Create es.po

### PR DESCRIPTION
**Pull request by advocatux**
Spanish translation added.
I've assumed there are two typos in the original .pot (Please correct me if I'm wrong):
* Line 243 `msgid "File exits"` should be `msgid "File exists"`
* Line 248 `msgid "Do you want to override %1?"` should be `msgid "Do you want to overwrite %1?"`

### CODE REVIEW

**Comment by timsueberkrueb** [comment]
Thank you! Yep, thanks for noticing those typos, will fix!

**Comment by timsueberkrueb** [comment]
Done, could you update your PR? Thanks a lot!
Please not that I use [Transifex](https://www.transifex.com/tim-sueberkrueb/crazy-mark/) for Crazy Mark's translations. I will upload your translations there unless you have any concerns.

**Comment by advocatux** [comment]
Done. PR updated. You can upload my translation to Transifex, no problem.
I'll do there the next Crazy Mark's translations.

**Comment by timsueberkrueb** [comment]
Cool, thank you! So I'm closing this one and merge your new PR (#5).

**Pull request closed without merging**
